export {default as heroGirlimg} from "./images/HeroGirlimg.webp"
export {default as PreLoader} from "./images/Preloader.gif"
export {default as bazaar} from "./images/bazaar.webp"
export {default as bustle} from "./images/bustle.webp"
export {default as versace} from "./images/versace.webp"
export {default as inStyle} from "./images/instyle.webp"
export {default as event1} from "./images/event1.webp"